import type { Metadata } from 'next';
import { revalidatePath } from 'next/cache';
import { MDXRemote } from 'next-mdx-remote/rsc';
import { createAdminClient } from '@/lib/supabase/admin';

export const dynamic = 'force-dynamic';
export const metadata: Metadata = {
  title: 'Content Review',
  robots: { index: false, follow: false },
};

function checkKey(key?: string): boolean {
  const secret = process.env.CONTENT_CRON_SECRET || process.env.CRON_SECRET;
  return !!secret && key === secret;
}

interface DraftRow {
  id: string;
  slug: string;
  title: string;
  description: string | null;
  body_mdx: string;
  keywords: string[] | null;
  product_refs: string[] | null;
  created_at: string;
}

/** Server action: flip a draft to published + revalidate the blog & sitemap. */
async function publishDraft(formData: FormData) {
  'use server';
  const key = formData.get('key')?.toString();
  if (!checkKey(key)) return;
  const id = formData.get('id')?.toString();
  if (!id) return;

  const supabase = createAdminClient();
  const now = new Date().toISOString();
  await supabase
    .from('blog_posts')
    .update({ status: 'published', published_at: now, updated_at: now })
    .eq('id', id);
  await supabase
    .from('content_topics')
    .update({ status: 'published', updated_at: now })
    .eq('blog_post_id', id);

  revalidatePath('/[locale]/blog', 'page');
  revalidatePath('/[locale]/blog/[slug]', 'page');
  revalidatePath('/sitemap.xml');
}

export default async function AdminContentPage({
  searchParams,
}: {
  searchParams: Promise<{ key?: string }>;
}) {
  const { key } = await searchParams;

  if (!checkKey(key)) {
    return (
      <main className="max-w-xl mx-auto px-4 py-24 text-center">
        <h1 className="text-xl font-bold text-[#0f172a]">Content Review</h1>
        <p className="mt-3 text-sm text-[#64748b]">
          Unauthorized. Append <code>?key=YOUR_SECRET</code> to the URL.
        </p>
      </main>
    );
  }

  const supabase = createAdminClient();
  const { data, error } = await supabase
    .from('blog_posts')
    .select('id,slug,title,description,body_mdx,keywords,product_refs,created_at')
    .eq('status', 'draft')
    .order('created_at', { ascending: false });

  const drafts = (data ?? []) as DraftRow[];

  return (
    <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <h1 className="text-2xl font-bold text-[#0f172a]">
        Content Review — {drafts.length} draft{drafts.length === 1 ? '' : 's'}
      </h1>
      <p className="mt-2 text-sm text-[#64748b]">
        Articles generated by the pipeline. Review, then publish. Reject by
        deleting the row in Supabase.
      </p>

      {error && (
        <p className="mt-6 text-sm text-red-600">Load error: {error.message}</p>
      )}

      {drafts.length === 0 && !error && (
        <p className="mt-10 text-[#64748b]">No drafts waiting. 🎉</p>
      )}

      <div className="mt-8 space-y-10">
        {drafts.map((d) => (
          <article
            key={d.id}
            className="border border-[#e2e8f0] rounded-xl p-6 bg-white shadow-sm"
          >
            <div className="flex items-start justify-between gap-4">
              <div>
                <h2 className="text-lg font-bold text-[#0f172a]">{d.title}</h2>
                <p className="text-xs text-[#94a3b8] mt-1">
                  /blog/{d.slug} · {new Date(d.created_at).toLocaleString('en-GB')}
                </p>
              </div>
              <form action={publishDraft}>
                <input type="hidden" name="id" value={d.id} />
                <input type="hidden" name="key" value={key} />
                <button
                  type="submit"
                  className="shrink-0 rounded-md bg-[#16a34a] hover:bg-[#15803d] text-white text-sm font-semibold px-4 py-2 transition-colors"
                >
                  Publish
                </button>
              </form>
            </div>

            {d.description && (
              <p className="mt-3 text-sm text-[#475569] italic">{d.description}</p>
            )}

            <div className="mt-2 flex flex-wrap gap-1.5">
              {(d.keywords ?? []).map((k) => (
                <span
                  key={k}
                  className="text-[11px] bg-orange-50 text-[#ea580c] px-2 py-0.5 rounded-full"
                >
                  {k}
                </span>
              ))}
              {(d.product_refs ?? []).map((s) => (
                <span
                  key={s}
                  className="text-[11px] bg-blue-50 text-[#1e3a8a] px-2 py-0.5 rounded-full"
                >
                  → /products/{s}
                </span>
              ))}
            </div>

            <details className="mt-4 group">
              <summary className="cursor-pointer text-sm font-semibold text-[#1e3a8a] select-none">
                Preview article
              </summary>
              <div className="prose prose-slate max-w-none mt-4 prose-headings:text-[#0f172a] prose-a:text-[#1e3a8a]">
                <MDXRemote source={d.body_mdx} />
              </div>
            </details>
          </article>
        ))}
      </div>
    </main>
  );
}
